version: "3"

services:
  pgsql:
    image: postgres:14-alpine3.15
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: bookings
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: pgsql
    volumes:
      - ./pgsql:/var/lib/postgresql/data